name: Auto Sync on Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to destination repo
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

          # add remote using your PAT (no trailing slash!)
          git remote add mirror https://x-access-token:${TARGET_PAT}@github.com/woopwoop132v/cloned.git
          git push mirror main --force
