name: Auto Sync on Merge to Main (Auto-Create Target Repo)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create destination repo if missing
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
          TARGET_USER: "woopwoop132v"          # 👈 destination GitHub username/org
          TARGET_REPO: "cloned"                # 👈 destination repo name
        run: |
          echo "🔍 Checking if https://github.com/${TARGET_USER}/${TARGET_REPO} exists..."
          STATUS=$(curl -o /dev/null -w "%{http_code}" -H "Authorization: token ${TARGET_PAT}" https://api.github.com/repos/${TARGET_USER}/${TARGET_REPO})

          if [ "$STATUS" -eq 404 ]; then
            echo "⚙️ Repository not found — creating it..."
            curl -X POST -H "Authorization: token ${TARGET_PAT}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/user/repos \
              -d "{\"name\":\"${TARGET_REPO}\", \"private\": false}"
            echo "✅ Repository created successfully."
          else
            echo "✅ Repository already exists (HTTP $STATUS)"
          fi

      - name: Push to destination repo
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
          TARGET_USER: "woopwoop132v"
          TARGET_REPO: "cloned"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

          # add destination as remote and push main branch
          git remote add mirror https://x-access-token:${TARGET_PAT}@github.com/${TARGET_USER}/${TARGET_REPO}.git
          git push mirror main --force
